# Generated by Django 2.2.17 on 2024-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0048_auto_20240401_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='docker_image',
            field=models.CharField(default='codalab/codalab-legacy:py37', max_length=128),
        ),
    ]
