# Generated by Django 2.2.28 on 2025-01-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0049_submission_docker_image'),
        ('competitions', '0051_merge_20241203_1313'),
    ]

    operations = [
    ]
